services:
  chain-bot:
    build: .
    ports:
      - "8000:8000"
    container_name: chain-bot
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      OPENAI_API_KEY: ${OPENAI_API_KEY}

    develop:
      watch:
        - action: restart
          path: ./agent.py
        - action: rebuild
          path: ./requirements.txt
