services:
  chain-api:
    build: .
    ports:
      - "8000:8000"
    container_name: chain-api
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    develop:
      watch:
        - action: restart
          path: ./main.py
        - action: restart
          path: ./document.py
        - action: restart
          path: ./uy_joy.py
        - action: restart
          path: ./avto.py
        - action: restart
          path: ./forma1.py
        - action: restart
          path: ./forma2.py
        - action: restart
          path: ./xmed.py
        - action: rebuild
          path: ./requirements.txt
